### PR TITLE
Added functionality for inserting a summary for each movie

### PR DESCRIPTION
**Pull request by dimivrn**
Hello and sorry for the delay. 

I added the functionality for inserting also a movie summary (description). Please review it and tell me if there is something not right.

### CODE REVIEW

**Comment by dimivrn** [comment]
Hi, i will resolve the conflicts and sent again today the request.

**Comment by shivanshsoni** [comment]
@dimivrn Okk

**Comment by dimivrn** [comment]
Hello, i resolved everything. I hope all is ok.

**Comment by shivanshsoni** [comment]
Ya everything looks fine

**Pull request merged**
