### PR TITLE
Code base improvements

### LINKED ISSUE #27: Import issue
The latest merge messed up with the import for `Movie` class and the SQLite database. I've fixed it, going to send a PR with a few more changes in UI and some code cleanup.

### PR DESCRIPTION
**Pull request by kartikarora**
- Added Android O support
- Replaced icon pngs with svgs
- Fixed #27 
- Improved #3 UI a little
- Refactored code a little to use Support Library

### CODE REVIEW

**Comment by shivanshsoni** [comment]
Please resolve conflicts

**Comment by kartikarora** [comment]
There weren't any when I submitted the PR. I'll fix it tomorrow.

**Comment by kartikarora** [comment]
@shivanshsoni You repo was in a bad state, especially with the files which should have been ignored. Too many merge conflicts with all the IDE specific files which really don't need to be checked in to VCS

I've refactored all of the changes made earlier to resolve conflicts. We don't really need a separate detail activity. I've added a provision for that in the editor activity. Also, support for vector drawables, Android O. Made the UI more material design (#3).

Please don't do a GitHub based merge, it creates a new merge commit which ruins the git history for all the forks. Simply do a fast forward pull and push.

**Comment by kartikarora** [comment]
Also, consider #27 to be fixed with this. And whenever there's a change in the database, please ensure that you update your DB helper accordingly.

**Comment by kartikarora** [comment]
Now my fork's git history is ruined! 

You repo has the same commits but with different commit hash, pull them into my fork will create a new merge commit!

https://help.github.com/articles/about-pull-request-merges/

Please always use rebase and merge!

**Pull request merged**
